package comm;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
            // Which is auto-generated by Spring, we will use it to handle the data
            UserMapper userMapper;

    @GetMapping(path = "/find")
    public @ResponseBody
    User findUserByName(@RequestParam String name) {
        return userMapper.findByName(name);
    }
}